# ---------------------------------------------------------------
# ---------------------------------------------------------------
# Theme Information Settings
# ---------------------------------------------------------------
# ---------------------------------------------------------------

# ---------------------------------------------------------------
# General Settings
# ---------------------------------------------------------------

hexo_theme_yin:
  title: Yin
  author: 拂衣
  website_link: https://zhao.center

# ---------------------------------------------------------------
# License Settings
# ---------------------------------------------------------------

# display licenses for the whole site
license:
  MIT: true
  GPLv3: false
  GPLv2: false
  CC: BY  # Please select the CC license you want (default is BY):
            # BY
            # BY-SA
            # BY-ND
            # BY-NC
            # BY-NC-SA
            # BY-NC-ND
          # Check those links for more details:
          # https://creativecommons.org/choose/
          # https://creativecommons.org/licenses/
          # YOU CAN ALSO SET THIS IN A SPECIFIC POST

# ---------------------------------------------------------------
# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------
# ---------------------------------------------------------------

# ---------------------------------------------------------------
# Image Settings
# ---------------------------------------------------------------

image:
  logo: /favicon/favicon.png
  favicon: /favicon/favicon.png

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

menu:
  home: /
  archives: /archives
  about: /about

# ---------------------------------------------------------------
# Contact Settings
# ---------------------------------------------------------------

contact:
  email:
  github: zhao-center
  telegram:
